// Generated by delombok at Fri Nov 14 09:29:31 CET 2014
package com.mzhang.api.lombokDemo;

public class Mountain1 {
  private final String name;
  private final double latitude;
  private final double longitude;
  private String country;

  @java.beans.ConstructorProperties({"name", "latitude", "longitude"})
  @java.lang.SuppressWarnings("all")
  public Mountain1(final String name, final double latitude, final double longitude) {
    this.name = name;
    this.latitude = latitude;
    this.longitude = longitude;
  }

  @java.lang.SuppressWarnings("all")
  public String getName() {
    return this.name;
  }

  @java.lang.SuppressWarnings("all")
  public double getLatitude() {
    return this.latitude;
  }

  @java.lang.SuppressWarnings("all")
  public double getLongitude() {
    return this.longitude;
  }

  @java.lang.SuppressWarnings("all")
  public String getCountry() {
    return this.country;
  }

  @java.lang.SuppressWarnings("all")
  public void setCountry(final String country) {
    this.country = country;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public boolean equals(final java.lang.Object o) {
    if (o == this) return true;
    if (!(o instanceof Mountain1)) return false;
    final Mountain1 other = (Mountain1)o;
    if (!other.canEqual((java.lang.Object)this)) return false;
    final java.lang.Object this$name = this.getName();
    final java.lang.Object other$name = other.getName();
    if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
    if (java.lang.Double.compare(this.getLatitude(), other.getLatitude()) != 0) return false;
    if (java.lang.Double.compare(this.getLongitude(), other.getLongitude()) != 0) return false;
    final java.lang.Object this$country = this.getCountry();
    final java.lang.Object other$country = other.getCountry();
    if (this$country == null ? other$country != null : !this$country.equals(other$country)) return false;
    return true;
  }

  @java.lang.SuppressWarnings("all")
  protected boolean canEqual(final java.lang.Object other) {
    return other instanceof Mountain1;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final java.lang.Object $name = this.getName();
    result = result * PRIME + ($name == null ? 0 : $name.hashCode());
    final long $latitude = java.lang.Double.doubleToLongBits(this.getLatitude());
    result = result * PRIME + (int)($latitude >>> 32 ^ $latitude);
    final long $longitude = java.lang.Double.doubleToLongBits(this.getLongitude());
    result = result * PRIME + (int)($longitude >>> 32 ^ $longitude);
    final java.lang.Object $country = this.getCountry();
    result = result * PRIME + ($country == null ? 0 : $country.hashCode());
    return result;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public java.lang.String toString() {
    return "Mountain1(name=" + this.getName() + ", latitude=" + this.getLatitude() + ", longitude=" + this.getLongitude() + ", country=" + this.getCountry() + ")";
  }
}