// Generated by delombok at Fri Nov 14 09:29:31 CET 2014
package com.mzhang.api.lombokDemo;

public class Mountain3 extends Mountain2 {

  private int kilometer;

  public static void main(String[] args) {
    Mountain3 mountain = new Mountain3();
    System.out.println(mountain);
    System.out.println(mountain.hashCode());
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public boolean equals(final java.lang.Object o) {
    if (o == this) return true;
    if (!(o instanceof Mountain3)) return false;
    final Mountain3 other = (Mountain3)o;
    if (!other.canEqual((java.lang.Object)this)) return false;
    if (this.kilometer != other.kilometer) return false;
    return true;
  }

  @java.lang.SuppressWarnings("all")
  protected boolean canEqual(final java.lang.Object other) {
    return other instanceof Mountain3;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    result = result * PRIME + this.kilometer;
    return result;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public java.lang.String toString() {
    return "Mountain3(super=" + super.toString() + ", kilometer=" + this.kilometer + ")";
  }
}